# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer0.edu.tw:
  anchorpeer.tn.edu.tw:
  peer0.tn.edu.tw:
  peer1.tn.edu.tw:
  anchorpeer.tc.edu.tw:
  peer0.tc.edu.tw:
  peer1.tc.edu.tw:

networks:
  test:
    name: fabric_test

services:

  orderer0.edu.tw:
    container_name: orderer0.edu.tw
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=EduOrderMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:17050
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations/ordererOrganizations/edu.tw/orderers/orderer0.edu.tw/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/edu.tw/orderers/orderer0.edu.tw/tls/:/var/hyperledger/orderer/tls
        - orderer0.edu.tw:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 17050:17050
    networks:
      - test

  anchorpeer.tn.edu.tw:
    container_name: anchorpeer.tn.edu.tw
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      # - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=anchorpeer.tn.edu.tw
      - CORE_PEER_ADDRESS=anchorpeer.tn.edu.tw:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=anchorpeer.tn.edu.tw:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=anchorpeer.tn.edu.tw:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=anchorpeer.tn.edu.tw:7051
      - CORE_PEER_LOCALMSPID=TnMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:17051
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/tn.edu.tw/peers/anchorpeer.tn.edu.tw/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/tn.edu.tw/peers/anchorpeer.tn.edu.tw/tls:/etc/hyperledger/fabric/tls
        - anchorpeer.tn.edu.tw:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 17051:17051
    networks:
      - test

  peer0.tn.edu.tw:
    container_name: peer0.tn.edu.tw
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      # - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.tn.edu.tw
      - CORE_PEER_ADDRESS=peer0.tn.edu.tw:1051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:1051
      - CORE_PEER_CHAINCODEADDRESS=peer0.tn.edu.tw:1052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:1052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.tn.edu.tw:1051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.tn.edu.tw:1051
      - CORE_PEER_LOCALMSPID=TnMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:11051
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/tn.edu.tw/peers/peer0.tn.edu.tw/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/tn.edu.tw/peers/peer0.tn.edu.tw/tls:/etc/hyperledger/fabric/tls
        - peer0.tn.edu.tw:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 1051:1051
      - 11051:11051
    networks:
      - test

  peer1.tn.edu.tw:
    container_name: peer1.tn.edu.tw
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      # - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.tn.edu.tw
      - CORE_PEER_ADDRESS=peer1.tn.edu.tw:2051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:2051
      - CORE_PEER_CHAINCODEADDRESS=peer1.tn.edu.tw:2052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:2052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.tn.edu.tw:2051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.tn.edu.tw:2051
      - CORE_PEER_LOCALMSPID=TnMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:12051
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/tn.edu.tw/peers/peer1.tn.edu.tw/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/tn.edu.tw/peers/peer1.tn.edu.tw/tls:/etc/hyperledger/fabric/tls
        - peer1.tn.edu.tw:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 2051:2051
      - 12051:12051
    networks:
      - test

  anchorpeer.tc.edu.tw:
    container_name: anchorpeer.tc.edu.tw
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      # - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=anchorpeer.tc.edu.tw
      - CORE_PEER_ADDRESS=anchorpeer.tc.edu.tw:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=anchorpeer.tc.edu.tw:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=anchorpeer.tc.edu.tw:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=anchorpeer.tc.edu.tw:9051
      - CORE_PEER_LOCALMSPID=TcMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:19051
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/tc.edu.tw/peers/anchorpeer.tc.edu.tw/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/tc.edu.tw/peers/anchorpeer.tc.edu.tw/tls:/etc/hyperledger/fabric/tls
        - anchorpeer.tc.edu.tw:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
      - 19051:19051
    networks:
      - test

  peer0.tc.edu.tw:
    container_name: peer0.tc.edu.tw
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      # - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.tc.edu.tw
      - CORE_PEER_ADDRESS=peer0.tc.edu.tw:3051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:3051
      - CORE_PEER_CHAINCODEADDRESS=peer0.tc.edu.tw:3052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:3052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.tc.edu.tw:3051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.tc.edu.tw:3051
      - CORE_PEER_LOCALMSPID=TcMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:13051
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/tc.edu.tw/peers/peer0.tc.edu.tw/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/tc.edu.tw/peers/peer0.tc.edu.tw/tls:/etc/hyperledger/fabric/tls
        - peer0.tc.edu.tw:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 3051:3051
      - 13051:13051
    networks:
      - test

  peer1.tc.edu.tw:
    container_name: peer1.tc.edu.tw
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      # - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.tc.edu.tw
      - CORE_PEER_ADDRESS=peer1.tc.edu.tw:4051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:4051
      - CORE_PEER_CHAINCODEADDRESS=peer1.tc.edu.tw:4052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:4052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.tc.edu.tw:4051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.tc.edu.tw:4051
      - CORE_PEER_LOCALMSPID=TcMSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:14051
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/tc.edu.tw/peers/peer1.tc.edu.tw/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/tc.edu.tw/peers/peer1.tc.edu.tw/tls:/etc/hyperledger/fabric/tls
        - peer1.tc.edu.tw:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 4051:4051
      - 14051:14051
    networks:
      - test

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - anchorpeer.tn.edu.tw
      - peer0.tn.edu.tw
      - peer1.tn.edu.tw
      - anchorpeer.tc.edu.tw
      - peer0.tc.edu.tw
      - peer1.tc.edu.tw
    networks:
      - test
